version: 0.2
phases:
  pre_build:
    commands:
      - echo starting pre build phase
      - echo build 2.2
      - echo default region is  $AWS_DEFAULT_REGION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Logging in to Amazon EKS...
      - aws eks --region us-east-1 update-kubeconfig --name eks-bacth-cluster --role-arn arn:aws:iam::347564148062:role/eksctl-eks-bacth-cluster-nodegrou-NodeInstanceRole-WG5KEEE9PA08

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - kubectl get svc
