version: 0.2
phases:
  pre_build:
    commands:
      - echo starting pre build phase
      - echo build 2.2
      - echo default region is  $AWS_DEFAULT_REGION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Logging in to Amazon EKS...
      - aws sts get-caller-identity
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...

      # - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::347564148062:role/eksctl-eks-bacth-cluster-nodegrou-NodeInstanceRole-WG5KEEE9PA08 --role-session-name codebuild-kubectl --duration-seconds 900)
      # - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      # - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      # - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      # - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      # - aws eks --region us-east-1 update-kubeconfig --name eks-bacth-cluster
      # - kubectl get svc
