version: 0.2
phases:
  pre_build:
    commands:
      - echo starting pre build phase
      - echo default region is  $AWS_DEFAULT_REGION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 347564148062.dkr.ecr.us-east-1.amazonaws.com/ci-cd:$IMAGE_TAG .
      - docker tag 347564148062.dkr.ecr.us-east-1.amazonaws.com/ci-cd:$IMAGE_TAG 347564148062.dkr.ecr.us-east-1.amazonaws.com/ci-cd:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 347564148062.dkr.ecr.us-east-1.amazonaws.com/ci-cd:$IMAGE_TAG
