apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: hello
          imagePullPolicy: Always
          image: 347564148062.dkr.ecr.us-east-1.amazonaws.com/ci-cd:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NODE_PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 3000
